### ISSUE TITLE
We havent added that +2 attribute thing under talent trees

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1074]
Update: A short term solution until we can do something more creative if we want
![image](https://user-images.githubusercontent.com/16277198/115809126-e4dbe800-a42e-11eb-9e7f-7c97b5eeae72.png)

Chaos has it already and regular dota has it, not good enough. 
![image](https://user-images.githubusercontent.com/16277198/115807108-4dc16100-a42b-11eb-8152-c915994867ba.png)

This is regular dota 2 
![image](https://user-images.githubusercontent.com/16277198/115807560-32a32100-a42c-11eb-854e-2abe293a0e80.png)

**Comment by Snoresville** [comment]
iirc we removed it to promote skilling your skills in the early game

**Comment by darklordabc** [comment]
@Snoresville why cant you do both? It looks like an oversight and it looks bad

**Comment by Snoresville** [comment]
https://discord.com/channels/501306949434867713/682631693172998165/830274326803775508

**Comment by Snoresville** [comment]
to summarise:
ability points are scarce, dont want to confuse players with a 100% detrimental choice
discussed with firetoad and aimc that it is not needed

**Comment by fcalife** [comment]
its not bad, HAVING that thing is bad. chaos allows you to summon creeps to other arenas too, should we add every stupid thing they did? close this abomination.

**Comment by Snoresville** [comment]
since the attribute bonus is re-implemented with the ability to refund the points, plus we have an overwhelming positive public opinion, it would be nice to have this. there are cases where players cant do anything with their skill points, and this could be a nice way to fill the gaps.

**Comment by fcalife** [comment]
It's overwhelming because the poll was worded like a happy fun time adventure on the land of unicorns and lets everyone assume the best implementation possible in their own heads is going to be added. In practice, whatever we do, some people will like, some won't.

Also usually I'm lacking skill points, not having too much (unless you mean after like level 30, but at that point +2 attributes is like nothing)

Re-add this if you want but without any changes it is just a pointless distraction.

**Comment by SanctusAnimus** [comment]
This is finished i believe? @Snoresville if everything is done, close and claim

**Comment by Snoresville** [comment]
yeah it's finished, sorry
