### ISSUE TITLE
Disallow the use of troll's rampage when the battle trance hasn't been unlocked yet.

### ISSUE THREAD

**Issue by Jakarooo** [arcadia-redux/custom_hero_clash_issues#1160]
if its not allowed to use wd's shard upgrade and jugg's aghanim upgrade when the ult is not yet unlocked, why is this? this is really op on early levels especially on the first pvp battle

**Comment by Draze22** [comment]
This is possible because of how Valve coded it as shown below and we're therefore leaving it in the game. It's only 70 attack speed or 25% status res for 5 seconds which is strong but not OP.
![image](https://user-images.githubusercontent.com/63279022/122588704-bda63d80-d0a2-11eb-9677-d2eba9383b6d.png)
