### ISSUE TITLE
Iceblast debuff doesn't apply to creeps it passes through

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1217]
![image](https://user-images.githubusercontent.com/63279022/119840120-09544400-bf48-11eb-90fd-2ff28cb130c3.png)

**Comment by lovro-m** [comment]
It is like this in vanilla dota. Maybe we should leave it like that?

**Comment by SanctusAnimus** [comment]
Due to the way creep effect is implemented, this one is impossible to fix without rewriting (cause debuff is applied from damage of the iceblast, and iceblast pass through deal no damage by itself, and doesn't do anything to creeps in general). Rewriting for such case is overkill, thus closing. 
Maybe should add ability note to clarify that only explosion affects creeps?
