### ISSUE TITLE
Bloodrage with Shard puts Echo Sabre on cooldown while in fountain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1792]
Definitely works fine against creeps and should also work fine in duels. Not at all a high priority to fix since it only does this in the fountain.

**Comment by SanctusAnimus** [comment]
Both of mentioned are vanilla though? Are you sure it's not a vanilla mechanic / bug / interaction?

**Comment by Draze22** [comment]
> Both of mentioned are vanilla though? Are you sure it's not a vanilla mechanic / bug / interaction?

Yep, doesn't happen in vanilla Dota.

**Comment by Draze22** [comment]
Not important enough to bother fixing.

**Comment by lovro-m** [comment]
Findings regarding this issue if anyone wants to deal with this at some point:
the culprit is this line here in the modifier_hero_refreshing

function modifier_hero_refreshing:CheckState()
    return {
        [MODIFIER_STATE_INVULNERABLE] = true,

for some reason if the hero is invulnerable bloodrage puts echo sabre on cooldown, I remove the line everything works fine. If we really need the heroes to be invulnerable in base idk the solution then. Mind you there are MODIFIER_PROPERTY_ABSOLUTE_NODAMAGE_* in hero refreshing so invulnerable might not be necessary.

There are 3 options:
remove the DOTA_UNIT_TARGET_FLAG_INVULNERABLE flag in bloodseeker_bloodrage and then you can't cast bloodrage in fountain
remove invulnerability in modifier_hero_refreshing
rewrite bloodrage
