### ISSUE TITLE
Prevent Chronosphere from being cast more than twice by one player during a round

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1870]
I don't mind if this is done by rewriting Chrono to give it 2 charges or through some other method that doesn't require rewriting chrono.

**Comment by Osamabinfrank** [comment]
Why twice? It will ruin the balance completely..
Save skills will become op. One false promise works longer than 2 chronos as well as aganimed borrowed time. Shadow dance and shadow rearm will become extremely op. This balance update will just ruin the ability to counter a lots of God builds and make some of the noobish ones op as well..
Why instead of nerfing its duration or aoe or increase cast time you want to completely destroy the skill to the ground?

**Comment by Osamabinfrank** [comment]
Why don't you just apply the thing you did with "split shot" and "marksmanship" thing with chrono and hook shot? And maybe add a 10 sec unstable cd when it gets casted? Limiting the amount of abilities won't help with chrono, the cast limit of chrono will just kill the useful ness of the skill and many combos, and make those save abilities op because now all you need to do is save up 1 of them and just outheal your opponents if you can't exterminate them. 

although its quite good for me as a main tank, but it will completely ruin the balance and fun parts of the game..
