### ISSUE TITLE
Reduce the gold gained by the final player based on how long it took them to finish the round

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1989]
This is to deter stalling.

- [ ] The final player/team starts gaining less gold for finishing the round 20s after the second last player/team finishes the round.
- [ ] They gain 2% less gold (additive stacking, 50s = 100% less gold) from finishing the round for every second that passes before they finishes the round.
- [ ] Only applies to FFA and Duos.
- [ ] Only applies to the first 19 rounds of the game.

Example:

- The second slowest player finishes the round in 30s.
- The slowest player finishes the round in 55s. Therefore they gain (55-(40+10)) * 2 = 10% less gold from finishing the round.

**Comment by Draze22** [comment]
This also has the added benefit of encouraging players to finish rounds quickly which will also speed up games where no players are stalling.

**Comment by jakmarles** [comment]
There are a lot of situations where str heroes can stall the round not on purpose due to not having aoe abilities, (this unusually happens to early game tanks) can you make the mechanic activate only if the creeps weren't been damaged for the last 5-10 seconds. Starting spells like bullwark+reincarnation for example on str heros (low att speed)  will make them stall the rounds not on purpose due to those abilities aren't helping him finish the pve round faster etc

**Comment by jakmarles** [comment]
Same goes for summoners with high cd summons

**Comment by Draze22** [comment]
> There are a lot of situations where str heroes can stall the round not on purpose due to not having aoe abilities, (this unusually happens to early game tanks) can you make the mechanic activate only if the creeps weren't been damaged for the last 5-10 seconds. Starting spells like bullwark+reincarnation for example on str heros (low att speed) will make them stall the rounds not on purpose due to those abilities aren't helping him finish the pve round faster etc

I could make that exception, but players who stall could easily abuse that by killing creeps as slowly as possible while still damaging them every 5-10s. Instead I'd prefer to buff builds that often suffer from not dealing enough damage if that becomes a problem.
