### ISSUE TITLE
Players get stuck at lvl 1 in their arena or fountain instead of being removed from the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#215]
![image](https://user-images.githubusercontent.com/63279022/82114614-1e2cc200-97a1-11ea-9ee3-bc857f0d24b1.png)

This seems to be caused by the player disconnecting during the picking phase and reconnecting after a few rounds into the game, possibly also requires having their team mate abandon before they reconnect in duos.

┆Issue is synchronized with this [Trello card](https://trello.com/c/lKdv2em4) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82640847-a9e59900-9c4e-11ea-8803-e0e31290e7ce.png)
![image](https://user-images.githubusercontent.com/63279022/82640860-b36f0100-9c4e-11ea-8993-2a2be131a0de.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/90104264-4ff4fb00-dd87-11ea-90e1-2b2898df6f8d.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/106338984-594c3280-62e9-11eb-9c8a-c655ded3dd1f.png)
![image](https://user-images.githubusercontent.com/63279022/106338987-5d785000-62e9-11eb-9fd6-37cc50d5a271.png)

**Comment by fcalife** [comment]
This is intentional and means they took too long to load (or crashed during load) and are effectively not participating in the game. The bug here is that they should be dead and show as eliminated, but instead are stuck in limbo, alive but useless, as shown in the screenshots.

**Comment by mmdts** [comment]
@fcalife Do they lose mmr if that happens?

The game often crashes in pick-phase here, and I have to restart it, so this just happened to me.
Usually reconnect right after I get randomed. Now I don't mind playing with a randomed hero, and other than feeling bad for the people who have to play as 9 instead of 10, I don't mind not participating in the game and finding the next one.

I would mind it though if I end up being considered last and losing rating for it, as I have no way of stopping the game from crashing during pick phase.

Cheers.
