### ISSUE TITLE
[7.28] test Aghanim's Shard upgrades (A-C)

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#611]
Test each hero's aghanim's shard upgrade, making sure it works properly. If any bugs arise, open a related issue.

If the upgrade requires another ability in order to work (e.g. Eclipse vs. Lucent Beam), make a note telling the players so, and open a issue requesting the ability to be reworked so that its shard upgrade works with no need of extra abilities.

* [ ] Abaddon (Aphotic Shield)
* [ ] Ancient Apparition (Ice Vortex)
* [ ] Anti-Mage (Counterspell)
* [ ] Arc Warden (Magnetic Field)
* [ ] Axe (Counter Helix)
* [ ] Bane (Fiend's Grip)
* [ ] Batrider (Flaming Lasso)
* [ ] Beastmaster (Call of the Wild: Hawk)
* [ ] Bloodseeker (Bloodrage)
* [ ] Bounty Hunter (Track)
* [ ] Brewmaster (Primal Split)
* [ ] Centaur (Double Edge)
* [ ] Chaos Knight (Chaos Bolt)
* [ ] Chen (Divine Favor)
* [ ] Clinkz (Skeleton Walk)

┆Issue is synchronized with this [Trello card](https://trello.com/c/gFYc7d3h) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[7.28] test Aghanim's Shard upgrades (A-C)](https://trello.com/c/gFYc7d3h/85-728-test-aghanims-shard-upgrades-a-c)

**Comment by lovro-m** [comment]
Abaddon (Curse of Avernus) WORKS 
Spells required: Mist Coil OR Aphotic Shield
Needs to be decided how to rework the spell. Maybe make it proc on other spells.

**Comment by lovro-m** [comment]
Ancient Apparition (Ice Vortex) WORKS
Spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Anti-Mage (Counterspell): DOES NOW WORK
Extra spells required: -
Only works on anti mage. Must be rewritten.

**Comment by lovro-m** [comment]
Arc Warden (Magnetic Field): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Axe (Counter Helix): DOES NOT WORK
Extra spells required: -
The helix part works. The attack speed increase is not shown on the client, but I'm pretty sure attack speed is increased.

**Comment by lovro-m** [comment]
Bane (Fiend's Grip): DOES NOT WORK
Extra spells required: -
Illusion instantly dies after grip is cast.

**Comment by lovro-m** [comment]
Batrider (Flaming Lasso): DOES NOT WORK
Extra spells required: -
Can only be cast on allies. Completely useless in solo ffa. Should be rewritten to be able to cast on self at least.

**Comment by lovro-m** [comment]
Beastmaster (Call of the Wild: Hawk): DOES NOT WORK
Extra spells required: -
Spell is not used at all. Should implement either our own new shard or add a new hawk spell with a shard ability. If the latter is decided hawk should be rewritten.

**Comment by lovro-m** [comment]
Bloodseeker (Bloodrage): WORKS
Extra spells required: -
Maybe it's imba, but it works.

**Comment by lovro-m** [comment]
Bounty Hunter (Track): WORKS BUT USELESS
Extra spells required: -
The spell works in duos. Ally track movement speed works, but the 600 vision around tracked target is completely useless. Needs either a rework or a buff.

**Comment by lovro-m** [comment]
Brewmaster (Primal Split): DOES NOT WORK
Extra spells required: -
Spell is not used at all. Needs primal split implementation before a shard one.

**Comment by lovro-m** [comment]
Centaur (Double Edge): WORKS
Extra spells required: -
The 15% slow works on both creeps and heroes. The strength gain should probably be changed that it is increased on creeps hit, not just on heroes.

**Comment by lovro-m** [comment]
Chaos Knight (Chaos Bolt): WORKS
Extra spells required: Phantasm
Needs to be rewritten so it spawns illusions without phantasm. It just increases cast range without it.

**Comment by lovro-m** [comment]
Chen (Divine Favor): USELESS
Extra spells required: -
Should be rewritten into something completely different. Teleporting allies serves no purpose.

**Comment by lovro-m** [comment]
Clinkz (Skeleton Walk): DOES NOT WORK
Extra spells required: -
The spell is called frostivus2018_clinkz_wind_walk so that fucks up the shard. Should be rewritten.

**Comment by Shushishtok** [comment]
> Abaddon (Curse of Avernus): WORKS
Extra spells required: Mist Coil OR Aphotic Shield
Needs to be decided how to rework the spell. Maybe make it proc on other spells.

Personally, I wouldn't make it proc on other spells - some high instance spells can make it very strong e.g. Shackles.

> Axe (Counter Helix): DOES NOT WORK
Extra spells required: -
The helix part works. The attack speed increase is not shown on the client, but I'm pretty sure attack speed is increased.

I'm fairly certain that Axe's Counter Helix was rewritten by @Snoresville , so we just need to make the attack speed shown clientside. Shouldn't be an issue.

> Bane (Fiend's Grip): DOES NOT WORK
Extra spells required: -
Illusion instantly dies after grip is cast.

Also rewritten, need to fix if that's the case.

> Batrider (Flaming Lasso): DOES NOT WORK
Extra spells required: -
Can only be cast on allies. Completely useless in solo ffa. Should be rewritten to be able to cast on self at least.

It does work then, just useless on solo, which is fine IMO. Not every shard needs to be viable on aghs/shards.

> Clinkz (Skeleton Walk): DOES NOT WORK
Extra spells required: -
The spell is called frostivus2018_clinkz_wind_walk so that fucks up the shard. Should be rewritten.

It doesn't fuck up the shard, it just has no shard support written into it. Need to add that into the ability.

------

I agree with everything else not noted above.

Note: I'm not the authority or part of the balance team, those are just my opinions.
