### ISSUE TITLE
[7.28] Update list of abilities that use charges

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#628]
Go through the 7.28 patch notes and add/remove charges to any abilities that have been changed accordingly. Remember our charge replenish system is custom-made (check if this patch added any proper charge manipulation api), and to update tooltips if necessary.

┆Issue is synchronized with this [Trello card](https://trello.com/c/7FBS8rQc) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
Newly added shards have no API or KV support (at least yet, lol), so do we want to hardcode charges into kv / lib just for mirana?

Flamebreak charges talent added.
Nether Swap charges removed.
Since we don't have Chen's Holy Persuation - skipped.
Ion Shell new charges are hardcoded into it - cannot override, skipped for now.

**Comment by fcalife** [comment]
Added charges to Scurry.

Acorn Shot charges are hardcoded. Skipped.

**Comment by fcalife** [comment]
This looks done?
