### ISSUE TITLE
[7.28] Aghanim's Shard upgrades reworks MEGATHREAD

### ISSUE THREAD

**Issue by lovro-m** [arcadia-redux/custom_hero_clash_issues#920]
These are the heroes whose spells are adjusted with Aghanim's shard AND require extra abilities for the shard to function properly.
Each of these spells should be rewritten to not require extra abilities.

- [ ] Abaddon (Curse of Avernus): Mist Coil AND/OR Aphotic Shield
- [x] Chaos Knight (Chaos Bolt): Phantasm [reworked in branch Feature/ChaosBolt_rewrite]
- [ ] Dark Willow (Cursed Crown): Bramble Maze
- [x] Earth Spirit (Stone Remnant): Gets provided with other es spells
- [ ] Earthshaker (Fissure): Aftershock, Enchant Totem, Echo Slam
- [x] Faceless Void (Time Walk): Reverse Time Walk [fixed in refactor]
- [x] Legion Commander (Duel): Overwhelming odds [fixed in new patch]
- [x] Meepo (Ransack): (Geostrike maybe) [fixed in new patch]
- [ ] Pudge (Dismember): Eject
- [ ] Rubick (Telekinesis): Telekinesis Land
- [x] Shadow Shaman (Shackles): Mass Serpent Ward [fixed in branch Feature/Shackles_rewrite]
- [ ] Slardar (Slithereen Crush): Corrosive Haze
- [x] Spectre (Dispersion): Haunt
- [ ] Ursa (Earthshock): Enrage
- [x] Venomancer (Venomous Gale): Plague Wards
- [ ] Weaver (The Swarm): Geminate Attack
- [x] Winter Wyvern (Cold Embrace): Splinter Blast [reworked in branch Feature/ColdEmbrace_rewrite]
- [ ] Wraith King (Reincarnation): Vampiric Spirit

These are the heroes whose spells should be rewritten completely because they don't work or are useless. Extra descriptions are written in the comments.

- [x]  Anti-Mage (Counterspell): [fixed in refactor]
- [x]  Axe (Counter Helix):
- [x]  Bane (Fiend's Grip): [fixed in new patch]
- [ ]  Beastmaster (Call of the Wild: Hawk):
- [ ]  Brewmaster (Primal Split):
- [x]  Centaur (Double Edge): Works on creeps at 1/3 power. [reworked in branch Feature/DoubleEdge_rewrite]
- [ ]  Chen (Divine Favor):
- [x]  Clinkz (Skeleton Walk): [reworked in branch Feature/SkeletonWalk_rewrite]
- [ ]  Elder Titan (Echo Stomp):
- [ ]  Lone Druid (Savage Roar):
- [x]  Lycan (Summon Wolves): Adds one extra wolf [reworked in branch Feature/SummonWolves_rewrite]
- [x]  Shadow Demon (Demonic Purge):
- [ ]  Treant (Nature's Guise): 
- [ ]  Visage (Gravekeeper's Cloak): 

All of these should be treated as separate issues.

**Comment by lovro-m** [comment]
Abaddon (Curse of Avernus): WORKS
Extra spells required: Mist Coil OR Aphotic Shield
Needs to be decided how to rework the spell. Maybe make it proc on other spells.

**Comment by lovro-m** [comment]
Chaos Knight (Chaos Bolt): WORKS
Extra spells required: Phantasm
Needs to be rewritten so it spawns illusions without phantasm. It just increases cast range without it.

**Comment by lovro-m** [comment]
Dark Willow (Cursed Crown): WORKS
Extra spells required: Bramble Maze
Should be rewritten to cast without the extra spell.

**Comment by lovro-m** [comment]
Earth Spirit (Stone Remnant): DOES NOT WORK
Extra spells required: Gets provided with other es spells
The shard should provide remnant AoE vision and 4 extra charges. The vision part is partially useless and the extra charges does not work.

**Comment by lovro-m** [comment]
Earthshaker (Fissure): DOES NOT WORK
Extra spells required: Aftershock, Enchant Totem, Echo Slam
Should be rewritten to not require aftershock and can be applied with any ability, not just es abilities.

**Comment by lovro-m** [comment]
Faceless Void (Time Walk): DOES NOT WORK
Extra spells required: Reverse Time Walk
Reverse time walk does not appear when the spell is cast.

**Comment by lovro-m** [comment]
Legion Commander (Duel): WORKS
Extra spells required: Overwhelming odds
Needs to be rewritten to not require overwhelming odds.

**Comment by lovro-m** [comment]
Meepo (Ransack): DOES NOT WORK
Extra spells required: (Geostrike maybe)
In vanilla probably uses hidden geostrike. Anyway, needs to be rewritten.

**Comment by lovro-m** [comment]
Pudge (Dismember): DOES NOT WORK
Extra spells required: EJECT
The eating an ally part works, but the eject spell is missing so the ally can stay inside you forever.

**Comment by lovro-m** [comment]
Rubick (Telekinesis): DOES NOT WORK
Extra spells required: Telekinesis Land
Ally and enemy targeting and tossing works. Only self targeting works. Self toss must be fixed.

**Comment by lovro-m** [comment]
Shadow Shaman (Shackles): WORKS
Extra spells required: Mass Serpent Ward
No extra remarks.

**Comment by lovro-m** [comment]
Slardar (Corrosive Haze): WORKS
Extra spells required: Slithereen Crush
No extra remarks.

**Comment by lovro-m** [comment]
Spectre (Dispersion): DOES NOT WORK
Extra spells required: Haunt
Only targets heroes and cannot test because haunt is not in the game. Needs to be rewritten completely.

**Comment by lovro-m** [comment]
Ursa (Fury Swipes): WORKS
Extra spells required: Enrage
Has to be rewritten without enrage required. Also this: #917

**Comment by lovro-m** [comment]
Venomancer (Venomous Gale): WORKS
Extra spells required: Plague Wards
Has to be adjusted to summon without plague wards.

**Comment by lovro-m** [comment]
Weaver (The Swarm): WORKS
Extra spells required: Geminate Attack
Has to be rewritten to not have to require Geminate Attack. Otherwise works.

**Comment by lovro-m** [comment]
Winter Wyvern (Cold Embrace): WORKS
Extra spells required: Splinter Blast
Has to be rewritten to not have to require Splinter Blast. Otherwise works.

**Comment by lovro-m** [comment]
Wraith King (Reincarnation): WORKS
Extra spells required: Vampiric Spirit
Has to be rewritten to not have to require Vampiric Spirit. Otherwise works. Skeletons only spawn near enemy heroes, not creeps.

**Comment by lovro-m** [comment]
----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by lovro-m** [comment]
Anti-Mage (Counterspell): DOES NOT WORK
Extra spells required: -
Only works on anti mage. Must be rewritten. Don't forget anti mage counterspell talent.

**Comment by lovro-m** [comment]
Axe (Counter Helix): DOES NOT WORK
Extra spells required: -
The helix part works. The attack speed increase is not shown on the client, but I'm pretty sure attack speed is increased.

**Comment by lovro-m** [comment]
Bane (Fiend's Grip): DOES NOT WORK
Extra spells required: -
Illusion instantly dies after grip is cast.

**Comment by lovro-m** [comment]
Beastmaster (Call of the Wild: Hawk): DOES NOT WORK
Extra spells required: -
Spell is not used at all. Should implement either our own new shard or add a new hawk spell with a shard ability. If the latter is decided hawk should be rewritten.

**Comment by lovro-m** [comment]
Brewmaster (Primal Split): DOES NOT WORK
Extra spells required: -
Spell is not used at all. Needs primal split implementation before a shard one.

**Comment by lovro-m** [comment]
Chen (Divine Favor): DOES NOT WORK
Extra spells required: -
Should be rewritten into something completely different. Teleporting allies serves no purpose. After being cast on an ally does nothing.

**Comment by lovro-m** [comment]
Clinkz (Skeleton Walk): DOES NOT WORK
Extra spells required: -
The spell is called frostivus2018_clinkz_wind_walk so that fucks up the shard. Should be rewritten.

**Comment by lovro-m** [comment]
Elder Titan (Echo Stomp): DOES NOT WORK
Extra spells required: -
Cannot test because echo stomp is not in the game.

**Comment by lovro-m** [comment]
Lone Druid (Savage Roar): DOES NOT WORK
Extra spells required: -
Cannot test because Savage Roar is not in the game.

**Comment by lovro-m** [comment]
Lycan (Summon Wolves): DOES NOT WORK
Extra spells required: -
Requires complete rework.

**Comment by lovro-m** [comment]
Shadow Demon (Demonic Purge): DOES NOT WORK
Extra spells required: -
The spell is already rewritten. Shard must be added to lua.

**Comment by lovro-m** [comment]
Treant (Nature's Guise): DOES NOT WORK
Extra spells required: -
Nature's Guise not in the game. Cannot test.

**Comment by lovro-m** [comment]
Visage (Gravekeeper's Cloak): DOES NOT WORK
Extra spells required: -
Gravekeeper's Cloak not in the game.

**Comment by AustraliaIsMyCity** [comment]
These are the heroes whose spells are adjusted with Aghanim's shard AND require extra abilities for the shard to function properly.
Each of these spells should be rewritten to not require extra abilities.

- [ ] Chaos Knight (Chaos Bolt): Phantasm [reworked in branch Feature/ChaosBolt_rewrite]
- [x] Earth Spirit (Stone Remnant): Gets provided with other es spells
- [x] Faceless Void (Time Walk): Reverse Time Walk [fixed in refactor]
- [x] Shadow Shaman (Shackles): Mass Serpent Ward [fixed in branch Feature/Shackles_rewrite]
- [ ] Spectre (Dispersion): Haunt
- [ ] Venomancer (Venomous Gale): Plague Wards
- [x] Winter Wyvern (Cold Embrace): Splinter Blast [reworked in branch Feature/ColdEmbrace_rewrite]

These are the heroes whose spells should be rewritten completely because they don't work or are useless. Extra descriptions are written in the comments.

- [x]  Anti-Mage (Counterspell): [fixed in refactor]
- [x]  Axe (Counter Helix):
- [x]  Bane (Fiend's Grip):
- [x]  Centaur (Double Edge): Works on creeps at 1/3 power. [reworked in branch Feature/DoubleEdge_rewrite]
- [ ]  Clinkz (Skeleton Walk):
- [x]  Lycan (Summon Wolves): Adds one extra wolf [reworked in branch Feature/SummonWolves_rewrite]
- [x]  Shadow Demon (Demonic Purge):


These are the heroes whose spells are broken without other abilities but not worth the time & upkeep to rewrite.
- Abaddon (Curse of Avernus): Mist Coil AND/OR Aphotic Shield
- Dark Willow (Cursed Crown): Bramble Maze
- Earthshaker (Fissure): Aftershock, Enchant Totem, Echo Slam
- Legion Commander (Duel): Overwhelming odds
- Pudge (Dismember): Eject
- Meepo (Ransack): (Geostrike maybe)
- Rubick (Telekinesis): Telekinesis Land
- Slardar (Slithereen Crush): Corrosive Haze
- Ursa (Earthshock): Enrage
- Weaver (The Swarm): Geminate Attack
- Wraith King (Reincarnation): Vampiric Spirit

These are the heroes whose spells don't work or are useless but not worth the time and upkeep to rewrite.
- Beastmaster (Call of the Wild: Hawk):
- Brewmaster (Primal Split):
- Chen (Divine Favor):
- Elder Titan (Echo Stomp):
- Lone Druid (Savage Roar):
- Treant (Nature's Guise):
- Visage (Gravekeeper's Cloak):

All of these should be treated as separate issues.

**Comment by Draze22** [comment]
Legion Commander's aghs shard got changed by Valve and works properly now.

**Comment by Draze22** [comment]
Seems like the decision was made to not bother remaking and upkeeping the rest of these shard abilities. Re-open if this is not the case.
