### ISSUE TITLE
Using hookshot while in front of a sentry in pvp might crash the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#958]
![image](https://user-images.githubusercontent.com/63279022/112456339-c989a880-8dae-11eb-9c58-07d4db94ef45.png)

**Comment by fcalife** [comment]
Due to the nonsensical nature of this issue, here's what I bet happened: the user [hit the camera dummy](https://github.com/arcadia-redux/custom_hero_clash_issues/issues/965), with the ability, and thought they were hitting a nearby sentry. "Crashes" in this message would mean they got moved to the sentry's position ("crashed into") the sentry, not that the game itself crashed.

**Comment by SanctusAnimus** [comment]
should be fixed
