### ISSUE TITLE
Track doesn't work and needs ability note, specifying amount of charges per round

### ISSUE THREAD

**Issue by SanctusAnimus** [arcadia-redux/custom_hero_clash_issues#960]

**Comment by Draze22** [comment]
Track also can't be cast on creeps atm and has a 180 second cd. The long cd might be intentional but it not being castable on creeps can't be.
![image](https://user-images.githubusercontent.com/63279022/112561881-33936380-8e2a-11eb-8290-3740a7d63e2c.png)
![image](https://user-images.githubusercontent.com/63279022/112561910-45750680-8e2a-11eb-9d07-9fa5ebd4b2e5.png)

**Comment by Draze22** [comment]
We pushed an update to fix track but it's unclear if it works yet.

**Comment by SanctusAnimus** [comment]
It does work though? But still misses an ability note

**Comment by Osamabinfrank** [comment]
> It does work though? But still misses an ability note

I think i saw the tooltip in the Russian translation. Not sure though as i didn't read what it said and neither took the skill. I remember i saw 4/3 sec cd
